# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnBaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnBaseApp

  target 'rnBaseAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'rnBaseApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnBaseApp-tvOS

  target 'rnBaseApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
