# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'rnBaseApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rnBaseApp
  def main_pod
      pod "JSONModel"

        pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

      end  
          main_pod
  end






